version: 3

vars:
  ARTISAN: php artisan

tasks:
  i:
    cmds:
      - |
        npx openapi-typescript http://localhost:8000/docs/api.json \
        --output resources/views/types/schema.d.ts \
        --infer-types --export-type

  lint:
    desc: Run PHPStan analysis
    cmds:
      - "{{.ARTISAN}} phpstan analyse"

  format:
    desc: Run PHP-CS-Fixer
    cmds:
      - "{{.ARTISAN}} php-cs-fixer fix --dry-run --diff"

  setup:
    desc: Setup the ide-helper
    cmds:
      - |
        composer require --dev barryvdh/laravel-ide-helper
        php artisan ide-helper:generate
        php artisan ide-helper:models

  dev:
    cmds:
      - composer dev

  route:
    desc: List all Laravel routes
    cmds:
      - "{{.ARTISAN}} route:list"

  run:migrate:
    desc: Run the local database migrate
    cmds:
      - "{{ .ARTISAN }} migrate"

  run:seed:
    desc: Run the local database seed
    cmds:
      - |
        {{- if .CLI_ARGS }}
        {{ .ARTISAN }} db:seed --class={{ .CLI_ARGS }}
        {{- else }}
        {{ .ARTISAN }} db:seed
        {{- end }}

  make:c:
    desc: Create a Laravel controller
    cmds:
      - "{{.ARTISAN}} make:controller {{.CLI_ARGS}}Controller --model={{.CLI_ARGS}} --api"

  make:migrate:
    desc: Create a Laravel migration
    cmds:
      - "{{.ARTISAN}} make:migration {{.CLI_ARGS}}"

  make:fs:
    desc: Create a Laravel seeder and factory
    cmds:
      - "{{.ARTISAN}} make:factory {{.CLI_ARGS}}Factory --model={{.CLI_ARGS}}"
      - "{{.ARTISAN}} make:seeder {{.CLI_ARGS}}Seeder"

  make:f:
    desc: Create a Laravel factory
    cmds:
      - "{{.ARTISAN}} make:factory {{.CLI_ARGS}}Factory --model={{.CLI_ARGS}}"

  make:s:
    desc: Create a Laravel seeder
    cmds:
      - "{{.ARTISAN}} make:seeder {{.CLI_ARGS}}Seeder"

  make:req:
    desc: Create a Laravel request
    cmds:
      - "{{.ARTISAN}} make:request {{.CLI_ARGS}}Request"

  make:m:
    desc: Create a Laravel middleware
    cmds:
      - "{{.ARTISAN}} make:middleware {{.CLI_ARGS}}Middleware"

  make:res:
    desc: Create a Laravel resource
    cmds:
      - "{{.ARTISAN}} make:resource {{.CLI_ARGS}}Resource"

  make:test:
    desc: Create a Laravel test
    cmds:
      - "{{.ARTISAN}} make:test {{.CLI_ARGS}}Test --unit"

  c:
    desc: Clear the Laravel cache
    cmds:
      - "{{.ARTISAN}} cache:clear"
      - "{{.ARTISAN}} config:clear"
      - "{{.ARTISAN}} route:clear"
      - "{{.ARTISAN}} view:clear"
      - "{{.ARTISAN}} event:clear"
