import { rootRoute } from "./__root"
import { createRoute } from "@tanstack/react-router"
import Container from "@/components/layouts/Container"

export const indexRoute = createRoute({
    getParentRoute: () => rootRoute,
    path: '/',
    component: Index,
})
function Index() {
    return (
        <>
            <title>Home</title>
            <meta name="description" content="Generated by create-t3-app" />

            <Container>
                <h1>Index</h1>
            </Container>
        </>
    )
}